### ISSUE TITLE
Can't get notes to appear on Sketch 65

### ISSUE THREAD

**Issue by taniarich** [abynim/sketch-artboard-notes#3]
Hi, I've just installed your Sketch artboard notes which I've used before (thanks!), however I'm having issues getting it to appear in the plugin menu.
![Screen Shot 2020-05-12 at 12 14 39 pm](https://user-images.githubusercontent.com/42991018/81630991-47b8b700-944a-11ea-920a-77c4924dfc04.png)

I can see it in the library but not the plugin menu to add it.
![Screen Shot 2020-05-12 at 12 16 47 pm](https://user-images.githubusercontent.com/42991018/81631098-7898ec00-944a-11ea-8fb4-569a0340f554.png)

**Comment by abynim** [comment]
Hi Tania. The plugin does not have any options that can be triggered via the menu. With Artboard Notes installed, when you select an artboard you'll see an input field in the inspector on the right. Use this field to add notes for your artboard.

Hope this helps!

**Comment by taniarich** [comment]
Oh my bad, I see it now and clearly not the one I was looking for.  Sorry about that!
